id: D4EE4D490
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:55:27+00:00'
last_modified: '2022-05-27T15:43:17.307797+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a1c7:
      image_group_id: I1PD95910
      title: བྱང་ཆུབ་ཏུ་སེམས་བསྐྱེད་པའི་ཆོ་ག།
      total_pages: 1498
      order: 65
      base_file: a1c7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
