id: P26664100
initial_creation_type: ocr
source_metadata:
  volumes:
    4ea87a5d2a72403dbb082a357496d278:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: བྱང་ཆུབ་ཏུ་སེམས་བསྐྱེད་པའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
